apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: boyu
spec:
  selector:
    app: playlist-api
  ports:
  - port: 52007  # 外部端口，使用指定的端口号
    targetPort: 5000  # 容器内部端口
  type: ClusterIP