apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlist-recommender-pvc
  namespace: boyu
spec:
  selector:
    matchLabels:
      namespace: boyu
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard