apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-web-deployment
  namespace: boyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-web
  template:
    metadata:
      labels:
        app: playlist-web
    spec:
      containers:
      - name: web-server
        image: severusy/playlist-web:v1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-web-service
  namespace: boyu
spec:
  selector:
    app: playlist-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort